project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: 1
files:
  - source: /i18n/languages/en.yaml
    translation: /i18n/languages/%locale%.yaml
    ignore:
      - /i18n/**/dist/**
    languages_mapping:
      locale:
        en: en
        ar: ar
        fr: fr
        hi: hi
        ja: ja
        nl: nl
        pl: pl
        pt-BR: pt-br
        zh-CN: zh-hans
        zh-TW: zh-hant
