project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: 1
files:
  - source: i18n/src/languages/en.yaml
    ignore:
      - i18n/**/dist/**
    translation: i18n/src/languages/%locale%.yaml
