project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: 1
# 只导出已翻译的条目
# skip_untranslated_strings: true
# 只导出已审核的翻译
# export_only_approved: true

files:
  - source: /i18n/src/en.yaml
    translation: /i18n/src/languages/%locale_with_underscore%.yaml
